[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mpremote>=1.26.1",
    "neopixel>=0.0.1",
    "ruff>=0.14.0",
]
